version: "3.3"

services:
  clickhouse-server:
    image: yandex/clickhouse-server:21.12.2.17
    container_name: mdw_cliclhouse
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    volumes:
      - ./data:/var/lib/clickhouse
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./users.xml:/etc/clickhouse-server/users.xml
