version: "3.3"

services:
  db:
    image: redis:${TAG}
    container_name: redis${TAG}
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ~/docker/data/redis${TAG}:/data
      - ./timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
